"""initial migrate

Revision ID: 41b032b1bf72
Revises: 
Create Date: 2023-10-02 22:00:01.933311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b032b1bf72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=False),
    sa.Column('resume_url', sa.String(length=255), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('job_listing_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_listing_id'], ['job_lists.id'], name=op.f('fk_job_applications_job_listing_id_job_lists')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_job_applications_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_joblisting_association',
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('jobs_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jobs_id'], ['job_lists.id'], name=op.f('fk_user_joblisting_association_jobs_id_job_lists')),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name=op.f('fk_user_joblisting_association_users_id_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_joblisting_association')
    op.drop_table('job_applications')
    op.drop_table('users')
    op.drop_table('job_lists')
    # ### end Alembic commands ###
