"""empty message

Revision ID: bc136dd50bfe
Revises: 452a18ed1fa7
Create Date: 2023-10-05 16:18:54.275975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc136dd50bfe'
down_revision = '452a18ed1fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_lists', schema=None) as batch_op:
        batch_op.drop_column('company_image')

    # ### end Alembic commands ###
